name: Build LaTeX document
on: [push]


jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lectures/01-introduction/txt/
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: lecture.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: lecture.pdf
